### PR TITLE
final changes made.

### PR DESCRIPTION
**Pull request by Tegadaniel**

### CODE REVIEW

**Comment by myklll** [comment]
Did you host it anywhere? @Tegadaniel

**Comment by Tegadaniel** [comment]
> Did you host it anywhere? @Tegadaniel

No I did not host anywhere.

**Comment by myklll** [comment]
Please deploy to any platform of your choice and share the url

**Comment by Tegadaniel** [comment]
> Please deploy to any platform of your choice and share the url

https://busha-frontend-test-tega.netlify.app/

Here is the URL above this message.

**Pull request closed without merging**
